apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: cithit/roger142:latest
        ports:
        - containerPort: 80
        env:
        - name: BUILD_NUMBER
          value: "BUILD_NUMBER_PLACEHOLDER"
        - name: ENV_NAME
          value: "DEV"
---
apiVersion: v1
kind: Service
metadata:
  name: dev-service
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32000
